# Generated by Django 3.1.4 on 2021-02-01 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('parents', '0002_auto_20210101_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mothers_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('place_birth', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_of_register', models.DateField(default=django.utils.timezone.now)),
                ('student_photo', models.ImageField(blank=True, upload_to='')),
                ('Student_class', models.ManyToManyField(to='classes.Classes')),
                ('student_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.parent')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
